### ISSUE TITLE
[Suggestion] Move the window references out of the state

### ISSUE THREAD

**Issue by AngelMunoz** [NicoVIII/Andromeda-for-GOG#51]
Hey there 😁 
this looks incredible!

I was recently working on something and I can't say I did find a way to remove stateful references from the state because I'm sure I've seen it somewhere else but

for example

```fsharp
            Program.mkProgram init update view
            |> Program.withHost this
            |> Program.withSyncDispatch syncDispatch
#if DEBUG
            |> Program.withConsoleTrace
#endif
            |> Program.runWith (settings, authentication, this)
```

on the first samples I put out for FuncUI I used the same approach, pass the window in the init fn and use `Program.runWith ...params...` (I'm sorry I didn't know what I was doing, pretty sure I still don't know)

however, that has it's gotchas mostly related with having non-comparable types in the record, making it hard to compare states if needed as well as having issues with the state serialization/deserialization

I think a better approach is to use the update function to pass the window (or any other services) like I did here
https://gitlab.com/AngelMunoz/Playsole/-/blob/master/Program.fs#L27
https://gitlab.com/AngelMunoz/Playsole/-/blob/master/Shell.fs#L48
https://gitlab.com/AngelMunoz/Playsole/-/blob/master/Shell.fs#L85

```fsharp
let updateWithPlayer (msg: Shell.Msg) (state: Shell.State) =
            Shell.update msg state Player.getPlayer.Value

Program.mkProgram Shell.init updateWithPlayer Shell.view
|> Program.run
```

```fsharp
let update msg state player =
    match msg with 
    | PlaySong index ->
        player.Play index
```
that way you always have a window/services available in your update function
I think in the case of your app it also can apply for the settings and auth information

what do you think?

**Comment by NicoVIII** [comment]
Thanks for looking into my spaghetti code! :smile: 

This sounds interesting and could simplify some things. I will definitely try that and see how it feels! :)
This is my first approach to implement stuff with MVU so I'm very thankful for every hint and ideas into different directions so I can find the way that works best for me ^.^

**Comment by AngelMunoz** [comment]
give me a few minutes and I'll send a draft 😁
